/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PrivateDrizzleIndexRouteImport } from './routes/_private/drizzle/index'
import { Route as PrivateCommentsTodoIdRouteImport } from './routes/_private/comments/$todoId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PrivateDrizzleIndexRoute = PrivateDrizzleIndexRouteImport.update({
  id: '/drizzle/',
  path: '/drizzle/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateCommentsTodoIdRoute = PrivateCommentsTodoIdRouteImport.update({
  id: '/comments/$todoId',
  path: '/comments/$todoId',
  getParentRoute: () => PrivateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/': typeof PrivateIndexRoute
  '/comments/$todoId': typeof PrivateCommentsTodoIdRoute
  '/drizzle': typeof PrivateDrizzleIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/': typeof PrivateIndexRoute
  '/comments/$todoId': typeof PrivateCommentsTodoIdRoute
  '/drizzle': typeof PrivateDrizzleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_private/': typeof PrivateIndexRoute
  '/_private/comments/$todoId': typeof PrivateCommentsTodoIdRoute
  '/_private/drizzle/': typeof PrivateDrizzleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/register' | '/' | '/comments/$todoId' | '/drizzle'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/register' | '/' | '/comments/$todoId' | '/drizzle'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_public/login'
    | '/_public/register'
    | '/_private/'
    | '/_private/comments/$todoId'
    | '/_private/drizzle/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_private/drizzle/': {
      id: '/_private/drizzle/'
      path: '/drizzle'
      fullPath: '/drizzle'
      preLoaderRoute: typeof PrivateDrizzleIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/comments/$todoId': {
      id: '/_private/comments/$todoId'
      path: '/comments/$todoId'
      fullPath: '/comments/$todoId'
      preLoaderRoute: typeof PrivateCommentsTodoIdRouteImport
      parentRoute: typeof PrivateRoute
    }
  }
}

interface PrivateRouteChildren {
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivateCommentsTodoIdRoute: typeof PrivateCommentsTodoIdRoute
  PrivateDrizzleIndexRoute: typeof PrivateDrizzleIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateCommentsTodoIdRoute: PrivateCommentsTodoIdRoute,
  PrivateDrizzleIndexRoute: PrivateDrizzleIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
